function languageDetailByCode(code) {
    [
        { code: 'aa', name: 'Afar', dir: 1, native: 'Afar' },
        { code: 'ab', name: 'Abkhazian', dir: 1, native: 'Аҧсуа' },
        { code: 'af', name: 'Afrikaans', dir: 1, native: 'Afrikaans' },
        { code: 'ak', name: 'Akan', dir: 1, native: 'Akana' },
        { code: 'am', name: 'Amharic', dir: 1, native: 'አማርኛ' },
        { code: 'an', name: 'Aragonese', dir: 1, native: 'Aragonés' },
        { code: 'ar', name: 'Arabic', dir: 0, native: 'العربية' },
        { code: 'as', name: 'Assamese', dir: 1, native: 'অসমীয়া' },
        { code: 'av', name: 'Avar', dir: 1, native: 'Авар' },
        { code: 'ay', name: 'Aymara', dir: 1, native: 'Aymar' },
        { code: 'az', name: 'Azerbaijani', dir: 1, native: 'Azərbaycanca / آذربايجان' },
        { code: 'ba', name: 'Bashkir', dir: 1, native: 'Башҡорт' },
        { code: 'be', name: 'Belarusian', dir: 1, native: 'Беларуская' },
        { code: 'bg', name: 'Bulgarian', dir: 1, native: 'Български' },
        { code: 'bh', name: 'Bihari', dir: 1, native: 'भोजपुरी' },
        { code: 'bi', name: 'Bislama', dir: 1, native: 'Bislama' },
        { code: 'bm', name: 'Bambara', dir: 1, native: 'Bamanankan' },
        { code: 'bn', name: 'Bengali', dir: 1, native: 'বাংলা' },
        { code: 'bo', name: 'Tibetan', dir: 1, native: 'བོད་ཡིག / Bod skad' },
        { code: 'br', name: 'Breton', dir: 1, native: 'Brezhoneg' },
        { code: 'bs', name: 'Bosnian', dir: 1, native: 'Bosanski' },
        { code: 'ca', name: 'Catalan', dir: 1, native: 'Català' },
        { code: 'ce', name: 'Chechen', dir: 1, native: 'Нохчийн' },
        { code: 'ch', name: 'Chamorro', dir: 1, native: 'Chamoru' },
        { code: 'co', name: 'Corsican', dir: 1, native: 'Corsu' },
        { code: 'cr', name: 'Cree', dir: 1, native: 'Nehiyaw' },
        { code: 'cs', name: 'Czech', dir: 1, native: 'Česky' },
        {
            code: 'cu',
            name: 'Old Church Slavonic / Old Bulgarian',
            dir: 1,
            native: 'словѣньскъ / slověnĭskŭ'
        },
        { code: 'cv', name: 'Chuvash', dir: 1, native: 'Чăваш' },
        { code: 'cy', name: 'Welsh', dir: 1, native: 'Cymraeg' },
        { code: 'da', name: 'Danish', dir: 1, native: 'Dansk' },
        { code: 'de', name: 'German', dir: 1, native: 'Deutsch' },
        { code: 'dv', name: 'Divehi', dir: 0, native: 'ދިވެހިބަސް' },
        { code: 'dz', name: 'Dzongkha', dir: 1, native: 'ཇོང་ཁ' },
        { code: 'ee', name: 'Ewe', dir: 1, native: 'Ɛʋɛ' },
        { code: 'el', name: 'Greek', dir: 1, native: 'Ελληνικά' },
        { code: 'en', name: 'English', dir: 1, native: 'English' },
        { code: 'eo', name: 'Esperanto', dir: 1, native: 'Esperanto' },
        { code: 'es', name: 'Spanish', dir: 1, native: 'Español' },
        { code: 'et', name: 'Estonian', dir: 1, native: 'Eesti' },
        { code: 'eu', name: 'Basque', dir: 1, native: 'Euskara' },
        { code: 'fa', name: 'Persian', dir: 0, native: 'فارسی' },
        { code: 'ff', name: 'Peul', dir: 1, native: 'Fulfulde' },
        { code: 'fi', name: 'Finnish', dir: 1, native: 'Suomi' },
        { code: 'fj', name: 'Fijian', dir: 1, native: 'Na Vosa Vakaviti' },
        { code: 'fo', name: 'Faroese', dir: 1, native: 'Føroyskt' },
        { code: 'fr', name: 'French', dir: 1, native: 'Français' },
        { code: 'fy', name: 'West Frisian', dir: 1, native: 'Frysk' },
        { code: 'ga', name: 'Irish', dir: 1, native: 'Gaeilge' },
        { code: 'gd', name: 'Scottish Gaelic', dir: 1, native: 'Gàidhlig' },
        { code: 'gl', name: 'Galician', dir: 1, native: 'Galego' },
        { code: 'gn', name: 'Guarani', dir: 1, native: "Avañe'ẽ" },
        { code: 'gu', name: 'Gujarati', dir: 1, native: 'ગુજરાતી' },
        { code: 'gv', name: 'Manx', dir: 1, native: 'Gaelg' },
        { code: 'ha', name: 'Hausa', dir: 0, native: 'هَوُسَ' },
        { code: 'he', name: 'Hebrew', dir: 0, native: 'עברית' },
        { code: 'hi', name: 'Hindi', dir: 1, native: 'हिन्दी' },
        { code: 'ho', name: 'Hiri Motu', dir: 1, native: 'Hiri Motu' },
        { code: 'hr', name: 'Croatian', dir: 1, native: 'Hrvatski' },
        { code: 'ht', name: 'Haitian', dir: 1, native: 'Krèyol ayisyen' },
        { code: 'hu', name: 'Hungarian', dir: 1, native: 'Magyar' },
        { code: 'hy', name: 'Armenian', dir: 1, native: 'Հայերեն' },
        { code: 'hz', name: 'Herero', dir: 1, native: 'Otsiherero' },
        { code: 'ia', name: 'Interlingua', dir: 1, native: 'Interlingua' },
        { code: 'id', name: 'Indonesian', dir: 1, native: 'Bahasa Indonesia' },
        { code: 'ie', name: 'Interlingue', dir: 1, native: 'Interlingue' },
        { code: 'ig', name: 'Igbo', dir: 1, native: 'Igbo' },
        { code: 'ii', name: 'Sichuan Yi', dir: 1, native: 'ꆇꉙ / 四川彝语' },
        { code: 'ik', name: 'Inupiak', dir: 1, native: 'Iñupiak' },
        { code: 'io', name: 'Ido', dir: 1, native: 'Ido' },
        { code: 'is', name: 'Icelandic', dir: 1, native: 'Íslenska' },
        { code: 'it', name: 'Italian', dir: 1, native: 'Italiano' },
        { code: 'iu', name: 'Inuktitut', dir: 1, native: 'ᐃᓄᒃᑎᑐᑦ' },
        { code: 'ja', name: 'Japanese', dir: 1, native: '日本語' },
        { code: 'jv', name: 'Javanese', dir: 1, native: 'Basa Jawa' },
        { code: 'ka', name: 'Georgian', dir: 1, native: 'ქართული' },
        { code: 'kg', name: 'Kongo', dir: 1, native: 'KiKongo' },
        { code: 'ki', name: 'Kikuyu', dir: 1, native: 'Gĩkũyũ' },
        { code: 'kj', name: 'Kuanyama', dir: 1, native: 'Kuanyama' },
        { code: 'kk', name: 'Kazakh', dir: 1, native: 'Қазақша' },
        { code: 'kl', name: 'Greenlandic', dir: 1, native: 'Kalaallisut' },
        { code: 'km', name: 'Cambodian', dir: 1, native: 'ភាសាខ្មែរ' },
        { code: 'kn', name: 'Kannada', dir: 1, native: 'ಕನ್ನಡ' },
        { code: 'ko', name: 'Korean', dir: 1, native: '한국어' },
        { code: 'kr', name: 'Kanuri', dir: 1, native: 'Kanuri' },
        { code: 'ks', name: 'Kashmiri', dir: 0, native: 'कश्मीरी / كشميري' },
        { code: 'ku', name: 'Kurdish', dir: 0, native: 'Kurdî / كوردی' },
        { code: 'kv', name: 'Komi', dir: 1, native: 'Коми' },
        { code: 'kw', name: 'Cornish', dir: 1, native: 'Kernewek' },
        { code: 'ky', name: 'Kirghiz', dir: 1, native: 'Kırgızca / Кыргызча' },
        { code: 'la', name: 'Latin', dir: 1, native: 'Latina' },
        { code: 'lb', name: 'Luxembourgish', dir: 1, native: 'Lëtzebuergesch' },
        { code: 'lg', name: 'Ganda', dir: 1, native: 'Luganda' },
        { code: 'li', name: 'Limburgian', dir: 1, native: 'Limburgs' },
        { code: 'ln', name: 'Lingala', dir: 1, native: 'Lingála' },
        { code: 'lo', name: 'Laotian', dir: 1, native: 'ລາວ / Pha xa lao' },
        { code: 'lt', name: 'Lithuanian', dir: 1, native: 'Lietuvių' },
        { code: 'lv', name: 'Latvian', dir: 1, native: 'Latviešu' },
        { code: 'mg', name: 'Malagasy', dir: 1, native: 'Malagasy' },
        { code: 'mh', name: 'Marshallese', dir: 1, native: 'Kajin Majel / Ebon' },
        { code: 'mi', name: 'Maori', dir: 1, native: 'Māori' },
        { code: 'mk', name: 'Macedonian', dir: 1, native: 'Македонски' },
        { code: 'ml', name: 'Malayalam', dir: 1, native: 'മലയാളം' },
        { code: 'mn', name: 'Mongolian', dir: 1, native: 'Монгол' },
        { code: 'mo', name: 'Moldovan', dir: 1, native: 'Moldovenească' },
        { code: 'mr', name: 'Marathi', dir: 1, native: 'मराठी' },
        { code: 'ms', name: 'Malay', dir: 1, native: 'Bahasa Melayu' },
        { code: 'mt', name: 'Maltese', dir: 1, native: 'bil-Malti' },
        { code: 'my', name: 'Burmese', dir: 1, native: 'Myanmasa' },
        { code: 'na', name: 'Nauruan', dir: 1, native: 'Dorerin Naoero' },
        { code: 'nd', name: 'North Ndebele', dir: 1, native: 'Sindebele' },
        { code: 'ne', name: 'Nepali', dir: 1, native: 'नेपाली' },
        { code: 'ng', name: 'Ndonga', dir: 1, native: 'Oshiwambo' },
        { code: 'nl', name: 'Dutch', dir: 1, native: 'Nederlands' },
        { code: 'nn', name: 'Norwegian Nynorsk', dir: 1, native: 'Norsk (nynorsk)' },
        { code: 'no', name: 'Norwegian', dir: 1, native: 'Norsk (bokmål / riksmål)' },
        { code: 'nr', name: 'South Ndebele', dir: 1, native: 'isiNdebele' },
        { code: 'nv', name: 'Navajo', dir: 1, native: 'Diné bizaad' },
        { code: 'ny', name: 'Chichewa', dir: 1, native: 'Chi-Chewa' },
        { code: 'oc', name: 'Occitan', dir: 1, native: 'Occitan' },
        { code: 'oj', name: 'Ojibwa', dir: 1, native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin' },
        { code: 'om', name: 'Oromo', dir: 1, native: 'Oromoo' },
        { code: 'or', name: 'Oriya', dir: 1, native: 'ଓଡ଼ିଆ' },
        { code: 'os', name: 'Ossetian / Ossetic', dir: 1, native: 'Иронау' },
        {
            code: 'pa',
            name: 'Panjabi / Punjabi',
            dir: 1,
            native: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي'
        },
        { code: 'pi', name: 'Pali', dir: 1, native: 'Pāli / पाऴि' },
        { code: 'pl', name: 'Polish', dir: 1, native: 'Polski' },
        { code: 'ps', name: 'Pashto', dir: 0, native: 'پښتو' },
        { code: 'pt', name: 'Portuguese', dir: 1, native: 'Português' },
        { code: 'qu', name: 'Quechua', dir: 1, native: 'Runa Simi' },
        { code: 'rm', name: 'Raeto Romance', dir: 1, native: 'Rumantsch' },
        { code: 'rn', name: 'Kirundi', dir: 1, native: 'Kirundi' },
        { code: 'ro', name: 'Romanian', dir: 1, native: 'Română' },
        { code: 'ru', name: 'Russian', dir: 1, native: 'Русский' },
        { code: 'rw', name: 'Rwandi', dir: 1, native: 'Kinyarwandi' },
        { code: 'sa', name: 'Sanskrit', dir: 1, native: 'संस्कृतम्' },
        { code: 'sc', name: 'Sardinian', dir: 1, native: 'Sardu' },
        { code: 'sd', name: 'Sindhi', dir: 1, native: 'सिनधि' },
        { code: 'se', name: 'Northern Sami', dir: 1, native: 'Davvisámegiella' },
        { code: 'sg', name: 'Sango', dir: 1, native: 'Sängö' },
        {
            code: 'sh',
            name: 'Serbo-Croatian',
            dir: 1,
            native: 'Srpskohrvatski / Српскохрватски'
        },
        { code: 'si', name: 'Sinhalese', dir: 1, native: 'සිංහල' },
        { code: 'sk', name: 'Slovak', dir: 1, native: 'Slovenčina' },
        { code: 'sl', name: 'Slovenian', dir: 1, native: 'Slovenščina' },
        { code: 'sm', name: 'Samoan', dir: 1, native: 'Gagana Samoa' },
        { code: 'sn', name: 'Shona', dir: 1, native: 'chiShona' },
        { code: 'so', name: 'Somalia', dir: 1, native: 'Soomaaliga' },
        { code: 'sq', name: 'Albanian', dir: 1, native: 'Shqip' },
        { code: 'sr', name: 'Serbian', dir: 1, native: 'Српски' },
        { code: 'ss', name: 'Swati', dir: 1, native: 'SiSwati' },
        { code: 'st', name: 'Southern Sotho', dir: 1, native: 'Sesotho' },
        { code: 'su', name: 'Sundanese', dir: 1, native: 'Basa Sunda' },
        { code: 'sv', name: 'Swedish', dir: 1, native: 'Svenska' },
        { code: 'sw', name: 'Swahili', dir: 1, native: 'Kiswahili' },
        { code: 'ta', name: 'Tamil', dir: 1, native: 'தமிழ்' },
        { code: 'te', name: 'Telugu', dir: 1, native: 'తెలుగు' },
        { code: 'tg', name: 'Tajik', dir: 1, native: 'Тоҷикӣ' },
        { code: 'th', name: 'Thai', dir: 1, native: 'ไทย / Phasa Thai' },
        { code: 'ti', name: 'Tigrinya', dir: 1, native: 'ትግርኛ' },
        { code: 'tk', name: 'Turkmen', dir: 1, native: 'Туркмен / تركمن' },
        { code: 'tl', name: 'Tagalog', dir: 1, native: 'Tagalog' },
        { code: 'tn', name: 'Tswana', dir: 1, native: 'Setswana' },
        { code: 'to', name: 'Tonga', dir: 1, native: 'Lea Faka-Tonga' },
        { code: 'tr', name: 'Turkish', dir: 1, native: 'Türkçe' },
        { code: 'ts', name: 'Tsonga', dir: 1, native: 'Xitsonga' },
        { code: 'tt', name: 'Tatar', dir: 1, native: 'Tatarça' },
        { code: 'tw', name: 'Twi', dir: 1, native: 'Twi' },
        { code: 'ty', name: 'Tahitian', dir: 1, native: 'Reo Mā`ohi' },
        { code: 'ug', name: 'Uyghur', dir: 1, native: 'Uyƣurqə / ئۇيغۇرچە' },
        { code: 'uk', name: 'Ukrainian', dir: 1, native: 'Українська' },
        { code: 'ur', name: 'Urdu', dir: 0, native: 'اردو' },
        { code: 'uz', name: 'Uzbek', dir: 1, native: 'Ўзбек' },
        { code: 've', name: 'Venda', dir: 1, native: 'Tshivenḓa' },
        { code: 'vi', name: 'Vietnamese', dir: 1, native: 'Việtnam' },
        { code: 'vo', name: 'Volapük', dir: 1, native: 'Volapük' },
        { code: 'wa', name: 'Walloon', dir: 1, native: 'Walon' },
        { code: 'wo', name: 'Wolof', dir: 1, native: 'Wollof' },
        { code: 'xh', name: 'Xhosa', dir: 1, native: 'isiXhosa' },
        { code: 'yi', name: 'Yiddish', dir: 0, native: 'ייִדיש' },
        { code: 'yo', name: 'Yoruba', dir: 1, native: 'Yorùbá' },
        { code: 'za', name: 'Zhuang', dir: 1, native: 'Cuengh / Tôô / 壮语' },
        { code: 'zh', name: 'Chinese', dir: 1, native: '中文' },
        { code: 'zu', name: 'Zulu', dir: 1, native: 'isiZulu' },
        { code: 'nb', name: 'Norwegian Bokmål', dir: 1, native: 'Norsk (bokmål)' }
    ]

    let result = null;
    for (let element of codeAndNameList) {
        i++;
        if (element.code == code) {
            result = element;
            break;
        }
    }
    return result;
}

module.exports.languageDetailByCode = languageDetailByCode;